// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using foodboxd_backend.Data;

#nullable disable

namespace foodboxd_backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251027180417_IngredientControllerMigration")]
    partial class IngredientControllerMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("foodboxd_backend.Models.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Description = "A Pizza Marguerita é um clássico napolitano, famosa por seus ingredientes simples e frescos que representam as cores da bandeira italiana.",
                            Name = "Pizza Marguerita",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/pizza_marguerita_so8rnj.png"
                        },
                        new
                        {
                            DishId = 2,
                            Description = "Um prato de massa italiano de Roma, feito com ovos, queijo duro, carne de porco curada e pimenta preta.",
                            Name = "Spaghetti Carbonara",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/spaghetti_carbonara_twqcuv.png"
                        },
                        new
                        {
                            DishId = 3,
                            Description = "Camadas de massa com molho à bolonhesa, molho branco e queijo, assadas à perfeição.",
                            Name = "Lasanha à Bolonhesa",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/lasanha_bolonhesa_gjtar8.png"
                        },
                        new
                        {
                            DishId = 4,
                            Description = "Um suculento hambúrguer de carne com queijo, alface, tomate em um pão macio.",
                            Name = "Hambúrguer Clássico",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/hamburguer_classico_ki7xad.png"
                        },
                        new
                        {
                            DishId = 5,
                            Description = "Peito de frango empanado, coberto com molho de tomate e queijo muçarela derretido.",
                            Name = "Frango à Parmegiana",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/frango_parmegiana_os4ych.png"
                        },
                        new
                        {
                            DishId = 6,
                            Description = "Arroz cremoso cozido lentamente com cogumelos frescos, queijo parmesão e um toque de vinho branco.",
                            Name = "Risoto de Cogumelos",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/risoto_cogumelos_pxqd7w.png"
                        },
                        new
                        {
                            DishId = 7,
                            Description = "Alface romana crocante com frango grelhado, croutons, queijo parmesão e molho Caesar cremoso.",
                            Name = "Salada Caesar",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/salada_caesar_cd6w4z.png"
                        },
                        new
                        {
                            DishId = 8,
                            Description = "Tortillas de milho macias recheadas com carne temperada, coentro fresco, cebola e um toque de limão.",
                            Name = "Tacos de Carne",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/tacos_carne_bnmami.png"
                        },
                        new
                        {
                            DishId = 9,
                            Description = "Rolinhos de arroz temperado com alga nori, recheados com salmão fresco.",
                            Name = "Sushi de Salmão",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/sushi_salmao_mxw2ro.png"
                        },
                        new
                        {
                            DishId = 10,
                            Description = "Uma sobremesa aerada e intensa, feita com chocolate meio amargo e creme de leite.",
                            Name = "Mousse de Chocolate",
                            Photo = "https://res.cloudinary.com/dslsxyvkp/image/upload/mousse_chocolate_lutgwl.png"
                        });
                });

            modelBuilder.Entity("foodboxd_backend.Models.Favorite", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("DishId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.HasKey("UserId", "DishId");

                    b.HasIndex("DishId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Massa de Pizza"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Molho de Tomate"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Queijo Muçarela"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Manjericão"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Azeite de Oliva"
                        },
                        new
                        {
                            IngredientId = 6,
                            Name = "Orégano"
                        },
                        new
                        {
                            IngredientId = 7,
                            Name = "Espaguete"
                        },
                        new
                        {
                            IngredientId = 8,
                            Name = "Ovo"
                        },
                        new
                        {
                            IngredientId = 9,
                            Name = "Queijo Parmesão"
                        },
                        new
                        {
                            IngredientId = 10,
                            Name = "Bacon"
                        },
                        new
                        {
                            IngredientId = 11,
                            Name = "Pimenta do Reino"
                        },
                        new
                        {
                            IngredientId = 12,
                            Name = "Massa de Lasanha"
                        },
                        new
                        {
                            IngredientId = 13,
                            Name = "Carne Moída"
                        },
                        new
                        {
                            IngredientId = 14,
                            Name = "Molho Branco"
                        },
                        new
                        {
                            IngredientId = 15,
                            Name = "Pão de Hambúrguer"
                        },
                        new
                        {
                            IngredientId = 16,
                            Name = "Hambúrguer de Carne"
                        },
                        new
                        {
                            IngredientId = 17,
                            Name = "Alface"
                        },
                        new
                        {
                            IngredientId = 18,
                            Name = "Tomate"
                        },
                        new
                        {
                            IngredientId = 19,
                            Name = "Queijo Cheddar"
                        },
                        new
                        {
                            IngredientId = 20,
                            Name = "Peito de Frango"
                        },
                        new
                        {
                            IngredientId = 21,
                            Name = "Farinha de Rosca"
                        },
                        new
                        {
                            IngredientId = 22,
                            Name = "Arroz Arbóreo"
                        },
                        new
                        {
                            IngredientId = 23,
                            Name = "Cogumelos"
                        },
                        new
                        {
                            IngredientId = 24,
                            Name = "Cebola"
                        },
                        new
                        {
                            IngredientId = 25,
                            Name = "Vinho Branco"
                        },
                        new
                        {
                            IngredientId = 26,
                            Name = "Caldo de Legumes"
                        },
                        new
                        {
                            IngredientId = 27,
                            Name = "Alface Romana"
                        },
                        new
                        {
                            IngredientId = 28,
                            Name = "Croutons"
                        },
                        new
                        {
                            IngredientId = 29,
                            Name = "Molho Caesar"
                        },
                        new
                        {
                            IngredientId = 30,
                            Name = "Tortillas de milho"
                        },
                        new
                        {
                            IngredientId = 31,
                            Name = "Carne em tiras"
                        },
                        new
                        {
                            IngredientId = 32,
                            Name = "Coentro"
                        },
                        new
                        {
                            IngredientId = 33,
                            Name = "Limão"
                        },
                        new
                        {
                            IngredientId = 34,
                            Name = "Arroz de Sushi"
                        },
                        new
                        {
                            IngredientId = 35,
                            Name = "Alga Nori"
                        },
                        new
                        {
                            IngredientId = 36,
                            Name = "Salmão"
                        },
                        new
                        {
                            IngredientId = 37,
                            Name = "Chocolate Meio Amargo"
                        },
                        new
                        {
                            IngredientId = 38,
                            Name = "Creme de Leite"
                        },
                        new
                        {
                            IngredientId = 39,
                            Name = "Açúcar"
                        });
                });

            modelBuilder.Entity("foodboxd_backend.Models.Publication", b =>
                {
                    b.Property<int>("PublicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PublicationId"));

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("longblob");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PublicationId");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Rating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("DishId");

                    b.HasIndex("UserId");

                    b.ToTable("Ratings");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RecipeId");

                    b.HasIndex("DishId")
                        .IsUnique();

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            DishId = 1,
                            Instructions = "Pré-aqueça o forno na temperatura mais alta possível (mínimo 220°C). Abra o disco de massa de pizza em uma superfície levemente enfarinhada e transfira para uma assadeira. Espalhe uma camada generosa de molho de tomate sobre a massa, deixando uma pequena borda. Distribua uniformemente a muçarela ralada por cima do molho. Regue com um fio de azeite e leve ao forno por 10-15 minutos, ou até a borda dourar e o queijo derreter. Retire do forno e espalhe as folhas de manjericão fresco por cima antes de servir."
                        },
                        new
                        {
                            RecipeId = 2,
                            DishId = 2,
                            Instructions = "Cozinhe o espaguete em água salgada fervente até ficar 'al dente'. Enquanto isso, frite o bacon em cubos até ficar crocante. Em uma tigela, bata as gemas com o queijo parmesão ralado e pimenta do reino. Escorra a massa, reservando um pouco da água. Fora do fogo, misture a massa com o bacon e, em seguida, adicione a mistura de ovos, mexendo rapidamente para criar um molho cremoso. Use a água do cozimento para ajustar a consistência, se necessário. Sirva imediatamente."
                        },
                        new
                        {
                            RecipeId = 3,
                            DishId = 3,
                            Instructions = "Em uma travessa, monte a lasanha alternando camadas: comece com molho à bolonhesa, seguido por uma camada de massa de lasanha, molho branco e queijo muçarela. Repita as camadas até preencher a travessa, finalizando com uma camada generosa de molho branco e queijo parmesão por cima. Leve ao forno pré-aquecido a 180°C por cerca de 30-40 minutos, ou até dourar."
                        },
                        new
                        {
                            RecipeId = 4,
                            DishId = 4,
                            Instructions = "Molde a carne no formato de hambúrguer e tempere com sal e pimenta. Grelhe em uma frigideira quente ou churrasqueira até atingir o ponto desejado. Nos últimos minutos, coloque a fatia de queijo cheddar sobre o hambúrguer para derreter. Toste levemente o pão e monte o lanche com o hambúrguer, alface fresca e rodelas de tomate."
                        },
                        new
                        {
                            RecipeId = 5,
                            DishId = 5,
                            Instructions = "Tempere o peito de frango e passe-o no ovo batido e depois na farinha de rosca. Frite em óleo quente até dourar dos dois lados. Em uma travessa, coloque o frango frito, cubra com molho de tomate e queijo muçarela. Leve ao forno pré-aquecido a 200°C apenas para gratinar o queijo, por cerca de 10 minutos."
                        },
                        new
                        {
                            RecipeId = 6,
                            DishId = 6,
                            Instructions = "Em uma panela, refogue a cebola picada na manteiga até ficar transparente. Adicione o arroz arbóreo e refogue por mais um minuto. Despeje o vinho branco e mexa até evaporar. Aos poucos, adicione o caldo de legumes quente, uma concha por vez, mexendo sempre até o arroz absorver o líquido. Quando o arroz estiver 'al dente', adicione os cogumelos fatiados, o queijo parmesão e mais uma colher de manteiga. Misture bem e sirva."
                        },
                        new
                        {
                            RecipeId = 7,
                            DishId = 7,
                            Instructions = "Grelhe o peito de frango temperado e corte em tiras. Em uma saladeira, misture a alface romana rasgada, os croutons e as lascas de parmesão. Adicione o frango grelhado por cima e regue tudo com o molho Caesar, misturando delicadamente para cobrir todos os ingredientes."
                        },
                        new
                        {
                            RecipeId = 8,
                            DishId = 8,
                            Instructions = "Tempere as tiras de carne com sal, pimenta e cominho. Grelhe em uma frigideira bem quente até dourarem. Aqueça as tortillas em outra frigideira ou no micro-ondas. Monte os tacos recheando cada tortilla com a carne grelhada, cebola picada e folhas de coentro. Sirva imediatamente com fatias de limão para espremer por cima."
                        },
                        new
                        {
                            RecipeId = 9,
                            DishId = 9,
                            Instructions = "Em uma esteira de bambu (sudare), coloque uma folha de alga nori com o lado brilhante para baixo. Umedeça as mãos e espalhe uma camada fina e uniforme de arroz de sushi sobre a alga, deixando uma borda livre. Posicione as tiras de salmão no centro do arroz. Enrole firmemente a alga com a ajuda da esteira. Com uma faca afiada e úmida, corte o rolo em 8 peças iguais."
                        },
                        new
                        {
                            RecipeId = 10,
                            DishId = 10,
                            Instructions = "Derreta o chocolate meio amargo em banho-maria ou no micro-ondas. Em outra tigela, bata o creme de leite fresco (ou as claras em neve com açúcar) até formar picos firmes. Incorpore delicadamente o chocolate derretido e já morno à mistura, com movimentos de baixo para cima para não perder a aeração. Despeje em taças individuais e leve à geladeira por pelo menos 4 horas antes de servir."
                        });
                });

            modelBuilder.Entity("foodboxd_backend.Models.RecipeIngredient", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<string>("MeasurementUnit")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double");

                    b.HasKey("RecipeId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("RecipeIngredient");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 1,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 2,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 3,
                            MeasurementUnit = "grama(s)",
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 4,
                            MeasurementUnit = "punhado(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 5,
                            MeasurementUnit = "fio(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 1,
                            IngredientId = 6,
                            MeasurementUnit = "pitada(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 7,
                            MeasurementUnit = "grama(s)",
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 8,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 2.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 9,
                            MeasurementUnit = "grama(s)",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 10,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 2,
                            IngredientId = 11,
                            MeasurementUnit = "pitada(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 12,
                            MeasurementUnit = "grama(s)",
                            Quantity = 250.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 13,
                            MeasurementUnit = "grama(s)",
                            Quantity = 300.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 2,
                            MeasurementUnit = "grama(s)",
                            Quantity = 300.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 14,
                            MeasurementUnit = "ml",
                            Quantity = 200.0
                        },
                        new
                        {
                            RecipeId = 3,
                            IngredientId = 3,
                            MeasurementUnit = "grama(s)",
                            Quantity = 250.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 15,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 16,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 17,
                            MeasurementUnit = "folha(s)",
                            Quantity = 2.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 18,
                            MeasurementUnit = "fatia(s)",
                            Quantity = 2.0
                        },
                        new
                        {
                            RecipeId = 4,
                            IngredientId = 19,
                            MeasurementUnit = "fatia(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 20,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 21,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 8,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 2,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 5,
                            IngredientId = 3,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 22,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 23,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 24,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 0.5
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 25,
                            MeasurementUnit = "ml",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 26,
                            MeasurementUnit = "ml",
                            Quantity = 500.0
                        },
                        new
                        {
                            RecipeId = 6,
                            IngredientId = 9,
                            MeasurementUnit = "grama(s)",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 27,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 20,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 28,
                            MeasurementUnit = "grama(s)",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 9,
                            MeasurementUnit = "grama(s)",
                            Quantity = 30.0
                        },
                        new
                        {
                            RecipeId = 7,
                            IngredientId = 29,
                            MeasurementUnit = "ml",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 30,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 3.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 31,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 24,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 0.25
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 32,
                            MeasurementUnit = "punhado(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 8,
                            IngredientId = 33,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 0.5
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 34,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 35,
                            MeasurementUnit = "folha(s)",
                            Quantity = 1.0
                        },
                        new
                        {
                            RecipeId = 9,
                            IngredientId = 36,
                            MeasurementUnit = "grama(s)",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 37,
                            MeasurementUnit = "grama(s)",
                            Quantity = 150.0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 38,
                            MeasurementUnit = "grama(s)",
                            Quantity = 100.0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 39,
                            MeasurementUnit = "grama(s)",
                            Quantity = 50.0
                        },
                        new
                        {
                            RecipeId = 10,
                            IngredientId = 8,
                            MeasurementUnit = "unidade(s)",
                            Quantity = 2.0
                        });
                });

            modelBuilder.Entity("foodboxd_backend.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Biography")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("Birthdate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("ProfilePhoto")
                        .HasColumnType("longblob");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Favorite", b =>
                {
                    b.HasOne("foodboxd_backend.Models.Dish", "Dish")
                        .WithMany("Favorites")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodboxd_backend.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Publication", b =>
                {
                    b.HasOne("foodboxd_backend.Models.Dish", "Dish")
                        .WithMany("Publications")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodboxd_backend.Models.User", "User")
                        .WithMany("Publications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Rating", b =>
                {
                    b.HasOne("foodboxd_backend.Models.Dish", "Dish")
                        .WithMany("Ratings")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodboxd_backend.Models.User", "User")
                        .WithMany("Ratings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("User");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Recipe", b =>
                {
                    b.HasOne("foodboxd_backend.Models.Dish", "Dish")
                        .WithOne("Recipe")
                        .HasForeignKey("foodboxd_backend.Models.Recipe", "DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");
                });

            modelBuilder.Entity("foodboxd_backend.Models.RecipeIngredient", b =>
                {
                    b.HasOne("foodboxd_backend.Models.Ingredient", "Ingredient")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("foodboxd_backend.Models.Recipe", "Recipe")
                        .WithMany("RecipeIngredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Dish", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Publications");

                    b.Navigation("Ratings");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Ingredient", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("foodboxd_backend.Models.Recipe", b =>
                {
                    b.Navigation("RecipeIngredients");
                });

            modelBuilder.Entity("foodboxd_backend.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Publications");

                    b.Navigation("Ratings");
                });
#pragma warning restore 612, 618
        }
    }
}
